/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./node_modules/flowbite-react/**/*.js",
    "./public/**/*.html",

    // Or if using `src` directory:
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    screens: {
      sm: "480px",
      md: "768px",
      lg: "976px",
      xl: "1440px",
    },
    colors: {
      white: "#ffffff",
      body: "#1e293b",
      black: "#000",
      backgroundColor: "#0C1117",
      notBlue: "#3457fe",
      notGreen: "#0fa226",
      primary: "rgb(var(--color-primary) / <alpha-value>)",
      secondary: "rgb(var(--color-secondary) / <alpha-value>)",
      success: "rgb(var(--color-success) / <alpha-value>)",
      info: "rgb(var(--color-info) / <alpha-value>)",
      warning: "rgb(var(--color-warning) / <alpha-value>)",
      pending: "rgb(var(--color-pending) / <alpha-value>)",
      danger: "rgb(var(--color-danger) / <alpha-value>)",
      light: "rgb(var(--color-light) / <alpha-value>)",
      dark: "rgb(var(--color-dark) / <alpha-value>)",
      darkmode: {
        50: "rgb(var(--color-darkmode-50) / <alpha-value>)",
        100: "rgb(var(--color-darkmode-100) / <alpha-value>)",
        200: "rgb(var(--color-darkmode-200) / <alpha-value>)",
        300: "rgb(var(--color-darkmode-300) / <alpha-value>)",
        400: "rgb(var(--color-darkmode-400) / <alpha-value>)",
        500: "rgb(var(--color-darkmode-500) / <alpha-value>)",
        600: "rgb(var(--color-darkmode-600) / <alpha-value>)",
        700: "rgb(var(--color-darkmode-700) / <alpha-value>)",
        800: "rgb(var(--color-darkmode-800) / <alpha-value>)",
        900: "rgb(var(--color-darkmode-900) / <alpha-value>)",
      },
      "blueGray-50": "#f8fafc",
      "blueGray-100": "#f1f5f9",
      "blueGray-200": "#e2e8f0",
      "blueGray-300": "#cbd5e1",
      "blueGray-400": "#94a3b8",
      "blueGray-500": "#64748b",
      "blueGray-600": "#475569",
      "blueGray-700": "#334155",
      "blueGray-800": "#1e293b",
      "blueGray-900": "#0f172a",

      "gray-100": "#f3f4f6",
      "gray-200": "#e5e7eb",
      "gray-300": "#d1d5db",
      "gray-400": "#9ca3af",
      "gray-500": "#6b7280",
      "gray-600": "#4b5563",
      "gray-700": "#374151",
      "gray-800": "#1f2937",
      "gray-900": "#111827",

      "blue-50": "#eff6ff",
      "blue-100": "#dbeafe",
      "blue-200": "#bfdbfe",
      "blue-300": "#93c5fd",
      "blue-400": "#60a5fa",
      "blue-500": "#3b82f6",
      "blue-600": "#2563eb",
      "blue-700": "#1d4ed8",
      "blue-800": "#1e40af",
      "blue-900": "#1e3a8a",
    },
    fontFamily: {
      sans: ["Graphik", "sans-serif"],
      serif: ["Merriweather", "serif"],
    },
    extend: {
      spacing: {
        128: "32rem",
        144: "36rem",
      },
      borderRadius: {
        "4xl": "2rem",
      },
    },
  },

  plugins: [require("flowbite/plugin")],
}
